### ISSUE TITLE
在线演示的与源码里Demo的代码不一样

### ISSUE THREAD

**Issue by joowoo** [cipchk/ngx-address#1]
在线演示的与源码里Demo的代码不一样
如果每个城市的id都不一样， 是不是可以增加直接按 id 赋值呢？

**Comment by cipchk** [comment]
如果你的城市编号是基于国家标准地址区域代码信息规则的话，可以直接使用 `ngModel` 双向绑定：

```
<ngx-address  [(ngModel)]="custom.id"></ngx-address>
```

如若编号**不符合国家标准地址区域代码**的话，只能你自行解析，最后使用 `[values]` 赋值：

```
<ngx-address  [(ngModel)]="custom.id" [values]="custom.values"></ngx-address>
```

细节见：https://github.com/cipchk/ngx-address#values

_另：DEMO中使用的是内置地址库，是符合国家标准的_，所以看起来不需要你任何处理。

**建议** 哪怕是你自己库，可以考虑加一个标准编码，然后使用内置地址库。一切都以标准编码来存储，算是比较上上策吧！

**Comment by joowoo** [comment]
谢了， 因为区域是企业里根据自己运营需要自己定义的区域，所以没法用国标， 
开始没注意到values这个， 看demo里代码盯着自定区域看了半天
最后还是自己解析，拼出value赋值了
