### ISSUE TITLE
请问怎么把项目跑起来？

### ISSUE THREAD

**Issue by baiyunchen** [cipchk/ngx-address#4]
clone项目后，npm i 安装依赖，然后npm start 在编译的时候报了一堆的错误，请问是本身就有问题，还是我的姿势不对？

**Comment by cipchk** [comment]
本身是一个angular cli项目，如果你想在本地运行demo的话。

```bash
ng serve
```

如果你希望二次开发，还需要再启动 `ngx-address` 子项目。

```bash
-- 编译ngx-address
npm run build
-- 或编译+监听
npm run build.watch
```

**Comment by baiyunchen** [comment]
谢谢！
